import { Link, useNavigate } from 'react-router-dom'

const metrics = [{ label: 'Total revenue', value: '$24,850', change: '12.5%', icon: '$' }, { label: 'Active members', value: '8,249', change: '8.4%', icon: '◎' }, { label: 'Open projects', value: '124', change: '4.7%', icon: '◇' }, { label: 'Conversion rate', value: '32.8%', change: '6.4%', icon: '%' }]
const activity = [{ icon: '$', tone: 'violet', title: 'New payment received', time: '2 minutes ago', value: '+$2,450' }, { icon: '+', tone: 'blue', title: 'New member joined', time: '24 minutes ago', value: '+1' }, { icon: '✓', tone: 'green', title: 'Project marked complete', time: '1 hour ago', value: 'Done' }, { icon: '★', tone: 'orange', title: 'New review received', time: '3 hours ago', value: '5.0' }]

const Dashboard = () => {
  const navigate = useNavigate()
  const logout = () => { localStorage.removeItem('isAuth'); navigate('/') }
  return <div className="dashboard">
    <aside className="sidebar"><Link to="/" className="navbar-logo dashboard-logo"><span className="logo-box">M</span><span>my<span>app</span></span></Link><nav className="side-nav" aria-label="Workspace navigation"><small>WORKSPACE</small><a className="active" href="#overview"><span>⌂</span>Overview</a><a href="#analytics"><span>◈</span>Analytics</a><a href="#projects"><span>▣</span>Projects <b>12</b></a><a href="#team"><span>♙</span>Team</a><a href="#settings"><span>⚙</span>Settings</a></nav><div className="sidebar-footer"><div className="upgrade-card"><span>✦</span><b>Unlock your potential</b><p>Get more insight with Pro.</p><button>Explore Pro <i>→</i></button></div><button className="logout" onClick={logout}><span>↪</span> Log out</button></div></aside>
    <main className="dashboard-main" id="overview"><header className="dashboard-header"><div><p className="eyebrow">OVERVIEW</p><h1>Good morning, Maya <span>✦</span></h1><p>Here’s a look at what’s moving today.</p></div><div className="header-actions"><button className="icon-button" aria-label="Notifications">♢<i /></button><button className="user-button" aria-label="Open profile"><span>MS</span><b>Maya S. <small>⌄</small></b></button></div></header>
      <section className="metric-grid" aria-label="Performance metrics">{metrics.map((metric) => <article className="metric-card" key={metric.label}><div><span>{metric.label}</span><b>{metric.icon}</b></div><strong>{metric.value}</strong><p><em>↗ {metric.change}</em> vs. last month</p></article>)}</section>
      <section className="dashboard-grid"><article className="panel chart-panel" id="analytics"><div className="panel-head"><div><p className="eyebrow">PERFORMANCE</p><h2>Revenue overview</h2></div><button className="period-button">Last 7 months <span>⌄</span></button></div><div className="chart-wrap"><div className="y-labels"><span>$30k</span><span>$20k</span><span>$10k</span><span>$0</span></div><div className="revenue-chart"><div className="grid-lines" />{[43, 61, 48, 76, 65, 91, 82].map((height, index) => <i key={index} style={{ height: `${height}%` }} />)}<div className="month-labels">{['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'].map((month) => <span key={month}>{month}</span>)}</div></div></div></article><article className="panel activity-panel"><div className="panel-head"><div><p className="eyebrow">ACTIVITY</p><h2>Recently happened</h2></div><button className="text-button">View all →</button></div><div className="activity-list">{activity.map((item) => <div className="activity-item" key={item.title}><span className={`activity-icon ${item.tone}`}>{item.icon}</span><div><b>{item.title}</b><small>{item.time}</small></div><strong>{item.value}</strong></div>)}</div></article></section>
      <section className="welcome-panel" id="projects"><div><p className="eyebrow">✦ READY WHEN YOU ARE</p><h2>Your next great idea<br />starts <em>right here.</em></h2><p>Create a project, invite your team, and turn momentum into something real.</p><button className="button button-dark">Create a project <span>→</span></button></div><div className="welcome-graphic"><span>✦</span><i /><i /><i /></div></section>
    </main>
  </div>
}

export default Dashboard
